name: Arcade
version: 1.0
main: com.github.incognitojam.arcade.Arcade

commands:
  arcade:
    description: Aracde plugin command
    usage: /arcade help
  machine:
    description: Arcade machine command
  display:
    description: Arcade display command
  game:
    description: Arcade game command
